/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.github.revxrsal.lamp.common)
    api(libs.com.github.revxrsal.lamp.bukkit)
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.com.github.ibanetchep.mscore.core.survival)
    compileOnly(libs.com.github.zrips.jobs)
    compileOnly(libs.fr.iban.lands)
}

group = "fr.iban"
version = "1.0"
description = "CustomItems"
java.sourceCompatibility = JavaVersion.VERSION_16

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
