name: CustomItems
version: '${project.version}'
main: fr.iban.customitems.CustomItemsPlugin
api-version: 1.19
authors: [ Iban ]
description: Custom items plugin
softdepend:
  - SurvivalCore
  - Lands
